import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";
import { readFile } from "node:fs/promises";
import { buildCoreAssets } from "./build-core-assets.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
await buildCoreAssets();
const licenses = await Promise.all(["LICENSE", "LICENSES/Formula-Library-MIT-1.5.0.txt", "LICENSES/MathLive-MIT.txt", "LICENSES/KaTeX-MIT.txt", "vendor/core/NOTICE", "vendor/core/THIRD-PARTY-LICENSES.txt"].map((path) => readFile(resolve(root, path), "utf8")));
await build({
  absWorkingDir: root,
  entryPoints: ["src/main.js"],
  bundle: true,
  platform: "browser",
  format: "cjs",
  target: "es2020",
  external: ["obsidian"],
  minifyWhitespace: true,
  minifySyntax: true,
  banner: { js: "/* Generated by npm run build. Edit src/ instead of this release artifact.\nCombined distribution: AGPL-3.0-only. Original plugin portions retain their MIT notice.\nCorresponding source: https://github.com/strangelion/obsidian-formula-library\n" + licenses.join("\n\n").replace(/\*\//g, "* /") + "\n*/" },
  outfile: "main.js",
  logLevel: "info",
});
await build({
  absWorkingDir: root,
  entryPoints: ["src/styles/index.css"],
  bundle: true,
  outfile: "styles.css",
  logLevel: "info",
});
