import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { resolve, dirname } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
await build({
  absWorkingDir: root,
  entryPoints: ["src/main.js"],
  bundle: true,
  platform: "browser",
  format: "cjs",
  target: "es2020",
  external: ["obsidian"],
  minifyWhitespace: true,
  minifySyntax: true,
  banner: { js: "/* Generated by npm run build. Edit src/ instead of this release artifact. */" },
  outfile: "main.js",
  logLevel: "info",
});
await build({
  absWorkingDir: root,
  entryPoints: ["src/styles/index.css"],
  bundle: true,
  outfile: "styles.css",
  logLevel: "info",
});
